
- name: Check if amg_dir exists
  stat: path={{FSMD_DIR}}
  register: fsmd

#- name: Add the remote host key
#  shell: 'ssh-keyscan -H git.code.sf.net >> /etc/ssh/ssh_known_hosts'

- name: Download the FSMDesigner source code
  git: repo=https://github.com/unihd-cag/fsmdesigner.git
       dest={{FSMD_DIR}} accept_hostkey=yes
  when: not fsmd.stat.exists

- name: change owner of fsmd sources
  file: path={{FSMD_DIR}} owner=vagrant group=vagrant recurse=yes
