- name: Install packages
  apt : pkg={{item}} state=present force=yes
  with_items:
    - build-essential
    - cmake
    - git
    - qt4-default

- name: Remove g++ in older ubuntu versions in order to install g++-5.
  apt : pkg={{item}} state=absent
  with_items:
    - g++
  when: ansible_distribution_version < "14.9"

- name: Install g++-5 .      
  apt : pkg={{item}} state=present
  with_items:
    - g++-5
  when: ansible_distribution_version < "14.9"

- name: Is g++ removed?
  stat: path=/usr/bin/g++
  register: gppIsPresent

- name: Is g++-5 present?
  stat: path=/usr/bin/g++-5
  register: gpp5IsPresent

# quick dirty hack
- name: Create a symbolic link g++ pointing to g++5
  shell: 'ln -s /usr/bin/g++-5 /usr/bin/g++'
  when: (not gppIsPresent.stat.exists and gpp5IsPresent.stat.exists)
