---
- hosts: ubuntu
  vars_files: 
    - ../common/vars.yml

  sudo: True

  tasks:
      - include: apt_update.yml
      - include: apt_cmake3_repo.yml
      - include: apt_gcc5_repo.yml

      - include: required_packages.yml
      - include: ../common/fsmd-git.yml
      - include: ../common/fsmd-build.yml

